-- Implemented connectors are active. Sitemap/HTML candidates stay paused until
-- their terms, robots policy, selectors, and change semantics are reviewed.
insert into public.sources
  (name, base_url, source_type, retrieval_method, connector_key, connector_config,
   is_primary_source, reliability_level, poll_interval_minutes, rate_limit_per_hour, active)
values
  ('OpenAI News', 'https://openai.com/news/rss.xml', 'Official company', 'RSS', 'rss', '{}', true, 'High', 60, 24, true),
  ('Hugging Face Blog', 'https://huggingface.co/blog/feed.xml', 'Official company', 'RSS', 'rss', '{}', true, 'High', 60, 24, true),
  ('GitHub Blog', 'https://github.blog/feed/', 'Official company', 'RSS', 'rss', '{}', true, 'High', 60, 24, true),
  ('Google AI Blog', 'https://blog.google/technology/ai/rss/', 'Official company', 'RSS', 'rss', '{}', true, 'High', 60, 24, true),
  ('arXiv AI and ML', 'https://export.arxiv.org/api/query', 'Research', 'API', 'arxiv', '{"categories":["cs.AI","cs.LG","stat.ML"]}', true, 'High', 720, 10, true),
  ('arXiv Language Vision Robotics and Security', 'https://export.arxiv.org/api/query', 'Research', 'API', 'arxiv', '{"categories":["cs.CL","cs.CV","cs.RO","cs.SE","cs.CR"]}', true, 'High', 720, 10, true),
  ('GitHub ollama/ollama', 'https://github.com/ollama/ollama', 'Open source', 'API', 'github', '{"repository":"ollama/ollama"}', true, 'High', 120, 30, true),
  ('GitHub vllm-project/vllm', 'https://github.com/vllm-project/vllm', 'Open source', 'API', 'github', '{"repository":"vllm-project/vllm"}', true, 'High', 120, 30, true),
  ('GitHub huggingface/transformers', 'https://github.com/huggingface/transformers', 'Open source', 'API', 'github', '{"repository":"huggingface/transformers"}', true, 'High', 120, 30, true),
  ('GitHub pytorch/pytorch', 'https://github.com/pytorch/pytorch', 'Open source', 'API', 'github', '{"repository":"pytorch/pytorch"}', true, 'High', 120, 30, true),
  ('GitHub tensorflow/tensorflow', 'https://github.com/tensorflow/tensorflow', 'Open source', 'API', 'github', '{"repository":"tensorflow/tensorflow"}', true, 'High', 120, 30, true),
  ('GitHub jax-ml/jax', 'https://github.com/jax-ml/jax', 'Open source', 'API', 'github', '{"repository":"jax-ml/jax"}', true, 'High', 120, 30, true),
  ('GitHub langchain-ai/langchain', 'https://github.com/langchain-ai/langchain', 'Open source', 'API', 'github', '{"repository":"langchain-ai/langchain"}', true, 'High', 120, 30, true),
  ('GitHub langfuse/langfuse', 'https://github.com/langfuse/langfuse', 'Open source', 'API', 'github', '{"repository":"langfuse/langfuse"}', true, 'High', 120, 30, true),
  ('GitHub modelcontextprotocol/specification', 'https://github.com/modelcontextprotocol/modelcontextprotocol', 'Open source', 'API', 'github', '{"repository":"modelcontextprotocol/modelcontextprotocol"}', true, 'High', 120, 30, true),
  ('GitHub ggml-org/llama.cpp', 'https://github.com/ggml-org/llama.cpp', 'Open source', 'API', 'github', '{"repository":"ggml-org/llama.cpp"}', true, 'High', 120, 30, true),
  ('GitHub NVIDIA/TensorRT-LLM', 'https://github.com/NVIDIA/TensorRT-LLM', 'Open source', 'API', 'github', '{"repository":"NVIDIA/TensorRT-LLM"}', true, 'High', 120, 30, true),
  ('GitHub QwenLM/Qwen', 'https://github.com/QwenLM/Qwen', 'Open source', 'API', 'github', '{"repository":"QwenLM/Qwen"}', true, 'High', 120, 30, true),
  ('Hugging Face OpenAI models', 'https://huggingface.co/openai', 'Model hub', 'API', 'huggingface', '{"author":"openai"}', true, 'Medium', 180, 20, true),
  ('Hugging Face Meta Llama models', 'https://huggingface.co/meta-llama', 'Model hub', 'API', 'huggingface', '{"author":"meta-llama"}', true, 'Medium', 180, 20, true),
  ('Hugging Face Mistral models', 'https://huggingface.co/mistralai', 'Model hub', 'API', 'huggingface', '{"author":"mistralai"}', true, 'Medium', 180, 20, true),
  ('Anthropic News', 'https://www.anthropic.com/news', 'Official company', 'Sitemap', 'sitemap', '{}', true, 'High', 60, 12, false),
  ('Google DeepMind', 'https://deepmind.google/discover/blog/', 'Official company', 'Sitemap', 'sitemap', '{}', true, 'High', 60, 12, false),
  ('Microsoft AI', 'https://blogs.microsoft.com/ai/', 'Official company', 'Sitemap', 'sitemap', '{}', true, 'High', 60, 12, false),
  ('Microsoft Research', 'https://www.microsoft.com/en-us/research/blog/', 'Research', 'Sitemap', 'sitemap', '{}', true, 'High', 720, 12, false),
  ('Meta AI', 'https://ai.meta.com/blog/', 'Official company', 'Sitemap', 'sitemap', '{}', true, 'High', 60, 12, false),
  ('NVIDIA AI', 'https://blogs.nvidia.com/blog/category/deep-learning/', 'Official company', 'Sitemap', 'sitemap', '{}', true, 'High', 60, 12, false),
  ('Mistral AI News', 'https://mistral.ai/news', 'Official company', 'Sitemap', 'sitemap', '{}', true, 'High', 60, 12, false),
  ('Cohere Blog', 'https://cohere.com/blog', 'Official company', 'Sitemap', 'sitemap', '{}', true, 'High', 60, 12, false),
  ('AWS Machine Learning', 'https://aws.amazon.com/blogs/machine-learning/', 'Official company', 'Sitemap', 'sitemap', '{}', true, 'High', 60, 12, false),
  ('Cloudflare AI', 'https://blog.cloudflare.com/tag/ai/', 'Official company', 'Sitemap', 'sitemap', '{}', true, 'High', 60, 12, false),
  ('Databricks AI', 'https://www.databricks.com/blog/category/engineering/ai-ml', 'Official company', 'Sitemap', 'sitemap', '{}', true, 'High', 60, 12, false),
  ('European AI Office', 'https://digital-strategy.ec.europa.eu/en/policies/ai-office', 'Government', 'Sitemap', 'sitemap', '{}', true, 'High', 360, 8, false),
  ('EUR-Lex', 'https://eur-lex.europa.eu/', 'Government', 'API', 'eurlex', '{}', true, 'High', 360, 8, false),
  ('European Data Protection Board', 'https://www.edpb.europa.eu/news/news_en', 'Government', 'Sitemap', 'sitemap', '{}', true, 'High', 360, 8, false),
  ('ENISA', 'https://www.enisa.europa.eu/news', 'Government', 'Sitemap', 'sitemap', '{}', true, 'High', 360, 8, false),
  ('NIST AI', 'https://www.nist.gov/artificial-intelligence', 'Government', 'Sitemap', 'sitemap', '{}', true, 'High', 360, 8, false),
  ('CISA Alerts', 'https://www.cisa.gov/news-events/cybersecurity-advisories', 'Government', 'Sitemap', 'sitemap', '{}', true, 'High', 360, 8, false),
  ('UK AI Security Institute', 'https://www.aisi.gov.uk/', 'Government', 'Sitemap', 'sitemap', '{}', true, 'High', 360, 8, false),
  ('OECD AI', 'https://oecd.ai/en/wonk', 'Government', 'Sitemap', 'sitemap', '{}', true, 'High', 360, 8, false),
  ('Hacker News', 'https://hacker-news.firebaseio.com/v0/', 'Discovery', 'API', 'hackernews', '{}', false, 'Low', 60, 30, false)
on conflict (name) do update set
  base_url = excluded.base_url,
  connector_config = excluded.connector_config || public.sources.connector_config,
  poll_interval_minutes = excluded.poll_interval_minutes;
